name: Dash Automation

on: repository_dispatch

jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: Response to Dash Main
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
          echo "We will initiate the next step (should run the e2e suite)"
      - name: PONG - Dispatch response to received PING
        if: github.event.action == 'ping'
        run: |
          curl -X POST https://api.github.com/repos/floreacosta/dash-main/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "pong", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'